export const CREATE_NODE = "CREATE_NODE";
export const DELETE_NODE = "DELETE_NODE";
export const CREATE_MEMBER = "CREATE_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const CREATE_SUPPORT = "CREATE_SUPPORT";
export const DELETE_SUPPORT = "DELETE_SUPPORT";
export const ADD_NODAL_LOAD = "ADD_NODAL_LOAD";
export const DELETE_NODAL_LOAD = "DELETE_NODAL_LOAD";
